server:
  port: ${PORT:${SERVER_PORT:8082}}

spring:
  application:
    name: catalog-service

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    registry-fetch-interval-seconds: 5
    healthcheck:
      enabled: true
    service-url:
      default-zone: http://localhost:8761/eureka

management:
  endpoints:
    web:
      exposure:
        include: info,health
        


  
message: Movies configuration server is alive for DEV!   