server:
  port: ${PORT:${SERVER_PORT:8083}}

spring:
  application:
    name: gateway
  cloud:
    gateway:
      discovery:
        locator:
          lowerCaseServiceId: true
          enabled: true
      routes:
        - id: catalogServiceRoute
          uri: lb://catalog-service/
          predicates:
            - Path=/catalog/**
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    registry-fetch-interval-seconds: 5
    healthcheck:
      enabled: true
    service-url:
      default-zone: http://localhost:8761/eureka
  instance:
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 20


management:
  endpoints:
    web:
      exposure:
        include: info, health
