server:
  port: ${PORT:${SERVER_PORT:8083}}

spring:
  application:
    name: gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: moviesServiceRoute
          uri: http://localhost:8081/
          predicates:
            - Path: /api/v1/movies/**

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    registry-fetch-interval-seconds: 5
    healthcheck:
      enabled: true
    service-url:
      default-zone: http://localhost:8761/eureka
      
  instance:
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 20
    

management:
  endpoints:
    web:
      exposure:
        include: info,health
        


  
message: Movies configuration server is alive for DEV!   